### ISSUE TITLE
Stream as an Applicative

### ISSUE THREAD

**Issue by mvcisback** [rickardlindberg/frp-arduino#1]
Hi, I was wondering if it'd be useful to reformulate stream as an Applicative.

Specifically,
`(~>) :: Stream a -> (Stream a -> Stream b) -> Stream b` is alot like `(<*>) :: f (a -> b) -> f a -> f b`

In some sense, `clock` is then:
`pure ([0..] :: [Int])`

which fits nicely since a clock is really just an enumeration.

**Comment by mvcisback** [comment]
To further expand, `Stream` feels like it should be the same as `Behavior` in http://conal.net/papers/push-pull-frp/push-pull-frp.pdf

**Comment by rickardlindberg** [comment]
Thank you for pointing me to that paper. I will study it later.

I've never used Applicative, so I'm not quite sure what your suggestion means. Will only the implementation change? Or will types change as well?

If you feel like your proposed change solves a problem (what can't we do if a Stream is not formulated as an Applicative?) with the current implementation, feel free to send a pull request and I'll merge it.

**Comment by mvcisback** [comment]
@rickardlindberg Using applicative has a number of benefits.

First is that it's a common Type Class with well understood semantics. In particular, there are a set of laws (identity, composition, homomorphism, interchange) which are expected to be satisfied. I suspect they already are (particularly given the similar structure in the paper).

In addition to giving well known semantics, it also provides an easy set of test cases that could be verified using quick check or something.

I don't think the types will change dramatically outside of the composition (~>).

**Comment by rickardlindberg** [comment]
I'm trying to understand this.

When we call the DSL functions, an internal representation is created. It can be found in DAG.hs. Essentially it is a bunch of streams, how they connect to eachother, and how they transform input to output. My understanding now is that having Stream be Applicative will only change the way we can write programs in the DSL but it will not change the internal representation that is built up. Does this match your understanding?

**Comment by mvcisback** [comment]
Sorry for the delay.

Yes I **think** the internal representation can remain unchanged.

The only reason you would need to change the internal code is if it fails to satisfy the `Applicative` Laws.
I would have to take a better look at

**Comment by mvcisback** [comment]
I'm going to close this. After working it out on paper, I don't think making Stream an Applicative is the right thing to do right now unless we allowed for Streams of Functions (which doesn't match what Stream is modeling).
